# SPDX-FileCopyrightText: Copyright (c) 2023-2025, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
- id: verify-alpha-spec
  name: verify-alpha-spec
  description: make sure RAPIDS packages have correct alpha spec
  entry: verify-alpha-spec
  language: python
  files: dependencies[.]yaml$
  args: [--fix]
  additional_dependencies:
    - --extra-index-url=https://pypi.anaconda.org/rapidsai-wheels-nightly/simple
    - .[alpha-spec]
- id: verify-codeowners
  name: verify-codeowners
  description: make sure .github/CODEOWNERS file is correct
  entry: verify-codeowners
  language: python
  files:
    (?x)
        ^[.]github/CODEOWNERS$
  args: [--fix]
- id: verify-conda-yes
  name: pass -y/--yes to conda
  description: make sure that all calls to conda pass -y/--yes
  entry: verify-conda-yes
  language: python
  types: [shell]
  args: [--fix]
- id: verify-copyright
  name: verify-copyright
  description: make sure copyright headers are up to date
  entry: verify-copyright
  language: python
  files: |
    (?x)
        [.](cmake|cpp|cu|cuh|h|hpp|sh|pxd|py|pyx|rs|java)$|
        CMakeLists[.]txt$|
        CMakeLists_standalone[.]txt$|
        meta[.]yaml$|
        pyproject[.]toml$|
        setup[.]cfg$
  args: [--fix]
- id: verify-pyproject-license
  name: verify-pyproject-license
  description: make sure pyproject.toml license is correct
  entry: verify-pyproject-license
  language: python
  files: |
    (?x)
        pyproject[.]toml$
  args: [--fix]
