# Copyright (c) 2023-2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- id: verify-alpha-spec
  name: verify-alpha-spec
  description: make sure RAPIDS packages have correct alpha spec
  entry: verify-alpha-spec
  language: python
  files: dependencies[.]yaml$
  args: [--fix]
  additional_dependencies:
    - --extra-index-url=https://pypi.anaconda.org/rapidsai-wheels-nightly/simple
    - .[alpha-spec]
- id: verify-conda-yes
  name: pass -y/--yes to conda
  description: make sure that all calls to conda pass -y/--yes
  entry: verify-conda-yes
  language: python
  types: [shell]
  args: [--fix]
- id: verify-codeowners
  name: verify-codeowners
  description: make sure .github/CODEOWNERS file is correct
  entry: verify-codeowners
  language: python
  files:
    (?x)
        ^[.]github/CODEOWNERS$
  args: [--fix]
- id: verify-copyright
  name: verify-copyright
  description: make sure copyright headers are up to date
  entry: verify-copyright
  language: python
  files: |
    (?x)
        [.](cmake|cpp|cu|cuh|h|hpp|sh|pxd|py|pyx)$|
        CMakeLists[.]txt$|
        CMakeLists_standalone[.]txt$|
        meta[.]yaml$|
        pyproject[.]toml$|
        setup[.]cfg$
  args: [--fix]
- id: verify-pyproject-license
  name: verify-pyproject-license
  description: make sure pyproject.toml license is correct
  entry: verify-pyproject-license
  language: python
  files: |
    (?x)
        pyproject[.]toml$
  args: [--fix]
