name: earliest-python-version
description: Get earliest supported Python version
outputs:
  python-version:
    value: ${{ steps.read-pyproject-toml.outputs.python-version }}

runs:
  using: composite
  steps:
    - id: read-pyproject-toml
      shell: bash
      run: |
        perl -e '
          while (<>) {
            if (/^requires-python = ">=(\d+\.\d+(\.\d+)?)"$/) {
              print("python-version=$1\n");
              exit(0);
            }
          }
          exit(1);
        ' pyproject.toml | tee -a "$GITHUB_OUTPUT"
