name: earliest-python-version
description: Get earliest supported Python version
outputs:
  python-version:
    value: ${{ steps.read-pyproject-toml.outputs.python-version }}

runs:
  using: composite
  steps:
    - id: read-pyproject-toml
      shell: bash
      run: |
        # Exit with 0 if `requires-python` is found, 1 otherwise
        sed -n -E '/^requires-python = / {
          s/^requires-python = ">=([0-9]+\.[0-9]+(\.[0-9]+)?)"$/python-version=\1/p;
          t matched
        }; $ q 1; b; :matched; q 0' pyproject.toml | tee -a "$GITHUB_OUTPUT"
